/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  public: {
    Tables: {
      about_content: {
        Row: {
          created_at: string | null
          features: Json | null
          founded_year: string | null
          id: string
          story: string[] | null
          subtitle: string | null
          title: string
          updated_at: string | null
          updated_by: string | null
        }
        Insert: {
          created_at?: string | null
          features?: Json | null
          founded_year?: string | null
          id?: string
          story?: string[] | null
          subtitle?: string | null
          title?: string
          updated_at?: string | null
          updated_by?: string | null
        }
        Update: {
          created_at?: string | null
          features?: Json | null
          founded_year?: string | null
          id?: string
          story?: string[] | null
          subtitle?: string | null
          title?: string
          updated_at?: string | null
          updated_by?: string | null
        }
        Relationships: []
      }
      admin_sections: {
        Row: {
          category: string
          created_at: string | null
          created_by: string | null
          description: string | null
          display_order: number | null
          enabled: boolean
          icon: string
          id: string
          label: string
          order_index: number
          slug: string
          updated_at: string | null
          updated_by: string | null
        }
        Insert: {
          category?: string
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          display_order?: number | null
          enabled?: boolean
          icon: string
          id?: string
          label: string
          order_index?: number
          slug: string
          updated_at?: string | null
          updated_by?: string | null
        }
        Update: {
          category?: string
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          display_order?: number | null
          enabled?: boolean
          icon?: string
          id?: string
          label?: string
          order_index?: number
          slug?: string
          updated_at?: string | null
          updated_by?: string | null
        }
        Relationships: []
      }
      artists: {
        Row: {
          bio: string | null
          created_at: string | null
          created_by: string | null
          genre: string | null
          id: string
          image_url: string | null
          is_active: boolean | null
          name: string
          social_links: Json | null
          updated_at: string | null
        }
        Insert: {
          bio?: string | null
          created_at?: string | null
          created_by?: string | null
          genre?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean | null
          name: string
          social_links?: Json | null
          updated_at?: string | null
        }
        Update: {
          bio?: string | null
          created_at?: string | null
          created_by?: string | null
          genre?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean | null
          name?: string
          social_links?: Json | null
          updated_at?: string | null
        }
        Relationships: []
      }
      audit_log: {
        Row: {
          action: string
          created_at: string | null
          id: string
          ip_address: unknown
          new_data: Json | null
          old_data: Json | null
          record_id: string
          session_id: string | null
          table_name: string
          user_agent: string | null
          user_id: string | null
          user_role: string | null
        }
        Insert: {
          action: string
          created_at?: string | null
          id?: string
          ip_address?: unknown
          new_data?: Json | null
          old_data?: Json | null
          record_id: string
          session_id?: string | null
          table_name: string
          user_agent?: string | null
          user_id?: string | null
          user_role?: string | null
        }
        Update: {
          action?: string
          created_at?: string | null
          id?: string
          ip_address?: unknown
          new_data?: Json | null
          old_data?: Json | null
          record_id?: string
          session_id?: string | null
          table_name?: string
          user_agent?: string | null
          user_id?: string | null
          user_role?: string | null
        }
        Relationships: []
      }
      event_artists: {
        Row: {
          artist_id: string
          created_at: string | null
          created_by: string | null
          event_id: string
          id: string
          is_headliner: boolean | null
          performance_time: string | null
          role: string | null
          stage: string | null
          updated_at: string | null
        }
        Insert: {
          artist_id: string
          created_at?: string | null
          created_by?: string | null
          event_id: string
          id?: string
          is_headliner?: boolean | null
          performance_time?: string | null
          role?: string | null
          stage?: string | null
          updated_at?: string | null
        }
        Update: {
          artist_id?: string
          created_at?: string | null
          created_by?: string | null
          event_id?: string
          id?: string
          is_headliner?: boolean | null
          performance_time?: string | null
          role?: string | null
          stage?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "event_artists_artist_id_fkey"
            columns: ["artist_id"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_artists_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_artists_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events_frontend"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_artists_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "partner_events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_artists_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "public_events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_artists_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "public_events_view"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          address: string | null
          attendees: number | null
          capacity: number | null
          category: string
          city: string | null
          contact_email: string | null
          contact_phone: string | null
          country: string | null
          created_at: string | null
          currency: string | null
          current_attendees: number | null
          date: string | null
          description: string | null
          end_date: string | null
          gallery_images_urls: Json | null
          id: string
          image: string | null
          image_url: string | null
          is_free: boolean | null
          is_virtual: boolean | null
          latitude: number | null
          location: string | null
          longitude: number | null
          max_attendees: number | null
          metadata: Json | null
          partner_id: string | null
          partner_logo_url: string | null
          partner_name: string | null
          price: number | null
          short_description: string | null
          social_links: Json | null
          start_date: string
          state: string | null
          status: string
          tags: string[] | null
          time: string | null
          title: string
          updated_at: string | null
          virtual_link: string | null
          website_url: string | null
          zip_code: string | null
        }
        Insert: {
          address?: string | null
          attendees?: number | null
          capacity?: number | null
          category: string
          city?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          country?: string | null
          created_at?: string | null
          currency?: string | null
          current_attendees?: number | null
          date?: string | null
          description?: string | null
          end_date?: string | null
          gallery_images_urls?: Json | null
          id?: string
          image?: string | null
          image_url?: string | null
          is_free?: boolean | null
          is_virtual?: boolean | null
          latitude?: number | null
          location?: string | null
          longitude?: number | null
          max_attendees?: number | null
          metadata?: Json | null
          partner_id?: string | null
          partner_logo_url?: string | null
          partner_name?: string | null
          price?: number | null
          short_description?: string | null
          social_links?: Json | null
          start_date: string
          state?: string | null
          status?: string
          tags?: string[] | null
          time?: string | null
          title: string
          updated_at?: string | null
          virtual_link?: string | null
          website_url?: string | null
          zip_code?: string | null
        }
        Update: {
          address?: string | null
          attendees?: number | null
          capacity?: number | null
          category?: string
          city?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          country?: string | null
          created_at?: string | null
          currency?: string | null
          current_attendees?: number | null
          date?: string | null
          description?: string | null
          end_date?: string | null
          gallery_images_urls?: Json | null
          id?: string
          image?: string | null
          image_url?: string | null
          is_free?: boolean | null
          is_virtual?: boolean | null
          latitude?: number | null
          location?: string | null
          longitude?: number | null
          max_attendees?: number | null
          metadata?: Json | null
          partner_id?: string | null
          partner_logo_url?: string | null
          partner_name?: string | null
          price?: number | null
          short_description?: string | null
          social_links?: Json | null
          start_date?: string
          state?: string | null
          status?: string
          tags?: string[] | null
          time?: string | null
          title?: string
          updated_at?: string | null
          virtual_link?: string | null
          website_url?: string | null
          zip_code?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_events_partner"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fk_events_partner"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners_frontend"
            referencedColumns: ["id"]
          },
        ]
      }
      gallery_items: {
        Row: {
          category: string
          created_at: string | null
          description: string | null
          display_order: number | null
          event_id: string | null
          file_metadata: Json | null
          id: string
          image_url: string
          metadata: Json | null
          partner_id: string | null
          processing_status: string | null
          status: string
          storage_path: string | null
          tags: string[] | null
          thumbnail_url: string | null
          title: string | null
          updated_at: string | null
          upload_session_id: string | null
        }
        Insert: {
          category?: string
          created_at?: string | null
          description?: string | null
          display_order?: number | null
          event_id?: string | null
          file_metadata?: Json | null
          id?: string
          image_url: string
          metadata?: Json | null
          partner_id?: string | null
          processing_status?: string | null
          status?: string
          storage_path?: string | null
          tags?: string[] | null
          thumbnail_url?: string | null
          title?: string | null
          updated_at?: string | null
          upload_session_id?: string | null
        }
        Update: {
          category?: string
          created_at?: string | null
          description?: string | null
          display_order?: number | null
          event_id?: string | null
          file_metadata?: Json | null
          id?: string
          image_url?: string
          metadata?: Json | null
          partner_id?: string | null
          processing_status?: string | null
          status?: string
          storage_path?: string | null
          tags?: string[] | null
          thumbnail_url?: string | null
          title?: string | null
          updated_at?: string | null
          upload_session_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "gallery_items_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gallery_items_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events_frontend"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gallery_items_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "partner_events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gallery_items_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "public_events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gallery_items_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "public_events_view"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gallery_items_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gallery_items_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners_frontend"
            referencedColumns: ["id"]
          },
        ]
      }
      hero_content: {
        Row: {
          created_at: string | null
          cta_link: string | null
          cta_text: string | null
          description: string | null
          id: string
          stats: Json | null
          subtitle: string | null
          title: string
          updated_at: string | null
          updated_by: string | null
        }
        Insert: {
          created_at?: string | null
          cta_link?: string | null
          cta_text?: string | null
          description?: string | null
          id?: string
          stats?: Json | null
          subtitle?: string | null
          title?: string
          updated_at?: string | null
          updated_by?: string | null
        }
        Update: {
          created_at?: string | null
          cta_link?: string | null
          cta_text?: string | null
          description?: string | null
          id?: string
          stats?: Json | null
          subtitle?: string | null
          title?: string
          updated_at?: string | null
          updated_by?: string | null
        }
        Relationships: []
      }
      partners: {
        Row: {
          address: string | null
          category: string
          city: string | null
          contact_email: string | null
          contact_phone: string | null
          country: string | null
          created_at: string | null
          description: string | null
          id: string
          latitude: number | null
          logo_url: string | null
          logourl: string | null
          longitude: number | null
          metadata: Json | null
          name: string
          social_links: Json | null
          state: string | null
          status: string
          updated_at: string | null
          website: string | null
          website_url: string | null
          zip_code: string | null
        }
        Insert: {
          address?: string | null
          category: string
          city?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          country?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          latitude?: number | null
          logo_url?: string | null
          logourl?: string | null
          longitude?: number | null
          metadata?: Json | null
          name: string
          social_links?: Json | null
          state?: string | null
          status?: string
          updated_at?: string | null
          website?: string | null
          website_url?: string | null
          zip_code?: string | null
        }
        Update: {
          address?: string | null
          category?: string
          city?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          country?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          latitude?: number | null
          logo_url?: string | null
          logourl?: string | null
          longitude?: number | null
          metadata?: Json | null
          name?: string
          social_links?: Json | null
          state?: string | null
          status?: string
          updated_at?: string | null
          website?: string | null
          website_url?: string | null
          zip_code?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          full_name: string | null
          id: string
          metadata: Json | null
          role: string | null
          updated_at: string | null
          username: string | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          full_name?: string | null
          id: string
          metadata?: Json | null
          role?: string | null
          updated_at?: string | null
          username?: string | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          full_name?: string | null
          id?: string
          metadata?: Json | null
          role?: string | null
          updated_at?: string | null
          username?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      team_members: {
        Row: {
          avatar_url: string | null
          bio: string | null
          created_at: string | null
          display_order: number | null
          email: string | null
          id: string
          image: string | null
          linkedin_url: string | null
          metadata: Json | null
          name: string
          social_links: Json | null
          status: string
          title: string | null
          twitter_handle: string | null
          updated_at: string | null
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string | null
          display_order?: number | null
          email?: string | null
          id?: string
          image?: string | null
          linkedin_url?: string | null
          metadata?: Json | null
          name: string
          social_links?: Json | null
          status?: string
          title?: string | null
          twitter_handle?: string | null
          updated_at?: string | null
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string | null
          display_order?: number | null
          email?: string | null
          id?: string
          image?: string | null
          linkedin_url?: string | null
          metadata?: Json | null
          name?: string
          social_links?: Json | null
          status?: string
          title?: string | null
          twitter_handle?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      user_permissions: {
        Row: {
          created_at: string | null
          id: string
          permissions: Json | null
          profile_id: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          permissions?: Json | null
          profile_id?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          permissions?: Json | null
          profile_id?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "user_permissions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      events_frontend: {
        Row: {
          address: string | null
          attendees: number | null
          capacity: number | null
          category: string | null
          city: string | null
          contact_email: string | null
          contact_phone: string | null
          country: string | null
          created_at: string | null
          currency: string | null
          current_attendees: number | null
          date: string | null
          description: string | null
          end_date: string | null
          gallery_images_urls: Json | null
          id: string | null
          image: string | null
          image_url: string | null
          is_free: boolean | null
          is_virtual: boolean | null
          latitude: number | null
          location: string | null
          longitude: number | null
          max_attendees: number | null
          metadata: Json | null
          partner_id: string | null
          partner_logo_url: string | null
          partner_name: string | null
          price: number | null
          short_description: string | null
          social_links: Json | null
          start_date: string | null
          state: string | null
          status: string | null
          tags: string[] | null
          time: string | null
          title: string | null
          updated_at: string | null
          virtual_link: string | null
          website_url: string | null
          zip_code: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_events_partner"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fk_events_partner"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners_frontend"
            referencedColumns: ["id"]
          },
        ]
      }
      partners_frontend: {
        Row: {
          address: string | null
          category: string | null
          city: string | null
          contact_email: string | null
          contact_phone: string | null
          country: string | null
          created_at: string | null
          description: string | null
          id: string | null
          latitude: number | null
          logo_url: string | null
          logourl: string | null
          longitude: number | null
          metadata: Json | null
          name: string | null
          social_links: Json | null
          state: string | null
          status: string | null
          updated_at: string | null
          website: string | null
          website_url: string | null
          zip_code: string | null
        }
        Relationships: []
      }
      public_events: {
        Row: {
          address: string | null
          attendees: number | null
          capacity: number | null
          category: string | null
          city: string | null
          contact_email: string | null
          contact_phone: string | null
          country: string | null
          created_at: string | null
          currency: string | null
          current_attendees: number | null
          date: string | null
          description: string | null
          end_date: string | null
          gallery_images_urls: Json | null
          id: string | null
          image: string | null
          image_url: string | null
          is_free: boolean | null
          is_virtual: boolean | null
          latitude: number | null
          location: string | null
          longitude: number | null
          max_attendees: number | null
          metadata: Json | null
          partner_id: string | null
          partner_logo_url: string | null
          partner_name: string | null
          price: number | null
          short_description: string | null
          social_links: Json | null
          start_date: string | null
          state: string | null
          status: string | null
          tags: string[] | null
          time: string | null
          title: string | null
          updated_at: string | null
          virtual_link: string | null
          website_url: string | null
          zip_code: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_events_partner"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fk_events_partner"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners_frontend"
            referencedColumns: ["id"]
          },
        ]
      }
      public_events_view: {
        Row: {
          address: string | null
          attendees: number | null
          capacity: number | null
          category: string | null
          city: string | null
          contact_email: string | null
          contact_phone: string | null
          country: string | null
          created_at: string | null
          currency: string | null
          current_attendees: number | null
          date: string | null
          description: string | null
          end_date: string | null
          gallery_images_urls: Json | null
          id: string | null
          image: string | null
          image_url: string | null
          is_free: boolean | null
          is_virtual: boolean | null
          latitude: number | null
          location: string | null
          longitude: number | null
          max_attendees: number | null
          metadata: Json | null
          partner_id: string | null
          partner_logo_url: string | null
          partner_name: string | null
          price: number | null
          short_description: string | null
          social_links: Json | null
          start_date: string | null
          state: string | null
          status: string | null
          tags: string[] | null
          time: string | null
          title: string | null
          updated_at: string | null
          virtual_link: string | null
          website_url: string | null
          zip_code: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_events_partner"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fk_events_partner"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners_frontend"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      delete_claim: {
        Args: {
          uid: string
          claim: string
        }
        Returns: string
      }
      get_claim: {
        Args: {
          uid: string
          claim: string
        }
        Returns: Json
      }
      get_claims: {
        Args: {
          uid: string
        }
        Returns: Json
      }
      get_my_claim: {
        Args: {
          claim: string
        }
        Returns: Json
      }
      get_my_claims: {
        Args: Record<PropertyKey, never>
        Returns: Json
      }
      set_claim: {
        Args: {
          uid: string
          claim: string
          value: Json
        }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"]
export type Insert<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Insert"]
export type Update<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Update"]
export type Enums<T extends keyof Database["public"]["Enums"]> = Database["public"]["Enums"][T]

// Helper types for common use cases
export type Event = Tables<"events">
export type Partner = Tables<"partners">
export type GalleryItem = Tables<"gallery_items">
export type TeamMember = Tables<"team_members">
export type HeroContent = Tables<"hero_content">
export type AboutContent = Tables<"about_content">
export type Profile = Tables<"profiles">
export type AdminSection = Tables<"admin_sections">
export type Artist = Tables<"artists">
export type AuditLog = Tables<"audit_log">
export type UserPermission = Tables<"user_permissions">

// Insert types
export type EventInsert = Insert<"events">
export type PartnerInsert = Insert<"partners">
export type GalleryItemInsert = Insert<"gallery_items">
export type TeamMemberInsert = Insert<"team_members">
export type HeroContentInsert = Insert<"hero_content">
export type AboutContentInsert = Insert<"about_content">
export type ProfileInsert = Insert<"profiles">
export type AdminSectionInsert = Insert<"admin_sections">
export type ArtistInsert = Insert<"artists">
export type AuditLogInsert = Insert<"audit_log">
export type UserPermissionInsert = Insert<"user_permissions">

// Update types
export type EventUpdate = Update<"events">
export type PartnerUpdate = Update<"partners">
export type GalleryItemUpdate = Update<"gallery_items">
export type TeamMemberUpdate = Update<"team_members">
export type HeroContentUpdate = Update<"hero_content">
export type AboutContentUpdate = Update<"about_content">
export type ProfileUpdate = Update<"profiles">
export type AdminSectionUpdate = Update<"admin_sections">
export type ArtistUpdate = Update<"artists">
export type AuditLogUpdate = Update<"audit_log">
export type UserPermissionUpdate = Update<"user_permissions">

// View types
export type EventsFrontend = Tables<"events_frontend">
export type PartnersFrontend = Tables<"partners_frontend">
export type PublicEvents = Tables<"public_events">
export type PublicEventsView = Tables<"public_events_view">