/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_41a567c3 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/qhimllczaejftnuymrsr/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.49.8';

const client = () => {
  const supabaseUrl = Deno.env.get('SUPABASE_URL');
  const supabaseServiceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

  if (!supabaseUrl || !supabaseServiceRoleKey) {
    throw new Error('Missing required environment variables for Supabase client');
  }

  return createClient(supabaseUrl, supabaseServiceRoleKey, {
    auth: {
      persistSession: false, // No persistence needed in edge functions
    },
  });
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from('kv_store_41a567c3').upsert({
      key,
      value
    }, { onConflict: 'key' }); // Explicitly specify conflict resolution

    if (error) {
      console.error('KV set error:', error);
      throw new Error(`Failed to set key-value pair: ${error.message}`);
    }
  } catch (err) {
    console.error('Unexpected error in set operation:', err);
    throw err;
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  try {
    const supabase = client();
    const { data, error } = await supabase.from('kv_store_41a567c3').select('value').eq('key', key).maybeSingle();

    if (error) {
      console.error('KV get error:', error);
      throw new Error(`Failed to retrieve key-value pair: ${error.message}`);
    }

    return data?.value;
  } catch (err) {
    console.error('Unexpected error in get operation:', err);
    throw err;
  }
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from('kv_store_41a567c3').delete().eq('key', key);

    if (error) {
      console.error('KV delete error:', error);
      throw new Error(`Failed to delete key-value pair: ${error.message}`);
    }
  } catch (err) {
    console.error('Unexpected error in delete operation:', err);
    throw err;
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  try {
    if (keys.length !== values.length) {
      throw new Error('Keys and values arrays must have the same length');
    }

    const supabase = client();
    const records = keys.map((k, i) => ({ key: k, value: values[i] }));
    const { error } = await supabase.from('kv_store_41a567c3').upsert(records, { onConflict: 'key' });

    if (error) {
      console.error('KV mset error:', error);
      throw new Error(`Failed to set multiple key-value pairs: ${error.message}`);
    }
  } catch (err) {
    console.error('Unexpected error in mset operation:', err);
    throw err;
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  try {
    if (keys.length === 0) return [];

    const supabase = client();
    const { data, error } = await supabase.from('kv_store_41a567c3').select('value, key').in('key', keys);

    if (error) {
      console.error('KV mget error:', error);
      throw new Error(`Failed to retrieve multiple key-value pairs: ${error.message}`);
    }

    // Create a map of key to value for efficient lookup
    const keyValueMap: Record<string, any> = {};
    data?.forEach((item) => {
      keyValueMap[item.key] = item.value;
    });

    // Return values in the same order as requested keys
    return keys.map(key => keyValueMap[key]);
  } catch (err) {
    console.error('Unexpected error in mget operation:', err);
    throw err;
  }
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  try {
    if (keys.length === 0) return;

    const supabase = client();
    const { error } = await supabase.from('kv_store_41a567c3').delete().in('key', keys);

    if (error) {
      console.error('KV mdel error:', error);
      throw new Error(`Failed to delete multiple key-value pairs: ${error.message}`);
    }
  } catch (err) {
    console.error('Unexpected error in mdel operation:', err);
    throw err;
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  try {
    const supabase = client();
    const { data, error } = await supabase.from('kv_store_41a567c3').select('key, value').ilike('key', `${prefix}%`);

    if (error) {
      console.error('KV getByPrefix error:', error);
      throw new Error(`Failed to search by prefix: ${error.message}`);
    }

    return data?.map((d) => d.value) ?? [];
  } catch (err) {
    console.error('Unexpected error in getByPrefix operation:', err);
    throw err;
  }
};