# ============================================
# WildOut! Project - Serena Configuration
# Next.js 16 + TypeScript + Supabase Project
# ============================================

# Project-specific languages for this Next.js/TypeScript project
# Primary: TypeScript for Next.js app development
# Secondary: Markdown for documentation, YAML for config files
languages:
  - typescript
  - markdown
  - yaml

# UTF-8 encoding for all text files (standard for web development)
encoding: 'utf-8'

# Use project's gitignore to exclude node_modules, build outputs, etc.
ignore_all_files_in_gitignore: true

# Additional paths to ignore for this Next.js project
ignored_paths:
  - '.next/' # Next.js build output
  - 'node_modules/' # Node.js dependencies
  - 'dist/' # Distribution files
  - 'build/' # Build artifacts
  - '*.log' # Log files
  - '*.tsbuildinfo' # TypeScript build info

# Project is NOT read-only (allow editing)
read_only: false

# ============================================
# TOOL CONFIGURATION - Optimized for WildOut Project
# ============================================

# Excluded tools (none excluded - we want full functionality)
# For WildOut project, we need all tools for:
# - Next.js development
# - TypeScript type checking
# - Supabase integration
# - Component development
# - Testing and debugging
excluded_tools: []

# ============================================
# PROJECT-SPECIFIC SETTINGS
# ============================================

# Initial prompt optimized for WildOut Next.js project
initial_prompt: 'activate_project'

# Project name
project_name: 'wildoutprojectrevamp'

# Included optional tools (empty for now, can be extended as needed)
included_optional_tools: []

# ============================================
# WILDOUT PROJECT STRUCTURE NOTES
# ============================================
# Key directories:
# - app/: Next.js App Router routes
# - components/: UI components (Shadcn UI)
# - lib/: Core utilities and Supabase client
# - providers/: Context providers
# - services/: Business logic
# - supabase/: Database and auth configuration
# - types/: TypeScript type definitions
# - utils/: Utility functions

# Tech Stack:
# - Next.js 16 (App Router)
# - TypeScript
# - Tailwind CSS 4
# - Supabase (Auth + Database)
# - TanStack Query (Data fetching)
# - Shadcn UI (Component library)

# Build System:
# - pnpm (package manager)
# - Turbo (build system)
# - Vitest (testing)

# ============================================
# RECOMMENDED WORKFLOW
# ============================================
# 1. Use symbolic tools for precise code modifications
# 2. Follow AGENTS.md guidelines in each directory
# 3. Maintain TypeScript type safety
# 4. Use Supabase RLS for security
# 5. Follow Shadcn UI patterns for components
